sudo: required

language: ruby

services:
  - docker

script:
  - make ci

after_success:
  - git add output
  - git commit -m 'Deploying output'
  - git push -f https://alexjpaz:$GITHUB_TOKEN@github.com/alexjpaz/earbudfm-scraper master

